# Generated by Django 2.0.7 on 2020-09-04 00:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_admisao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            managers=[
                ('funcionario', django.db.models.manager.Manager()),
            ],
        ),
    ]
