# Generated by Django 2.0.7 on 2020-09-17 22:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientes',
            managers=[
                ('clientes', django.db.models.manager.Manager()),
            ],
        ),
    ]
